import Layout from '../components/Layout'
import Image from "next/image";
import mobileProfilePic from "../../public/images/profile/developer-pic-1-1.png"
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '../components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '../components/Icons';
import HireMe from '../components/HireMe';
import programmingImg from "../../public/images/svgs/programming.svg"
import Head from 'next/head'
import TransitionEffect from '../components/TransitionEffect'

export default function Home() {
  const title = "Transforming Ideas into Interactive Realities"
  const description = "As a versatile full-stack developer, I bring ideas to life through cutting-edge web applications. Discover my projects and insights, reflecting my expertise in React.js and modern web solutions."

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by next app"></meta>
      </Head>
      <TransitionEffect />
      <main className='flex items-start w-full min-h-screen md:min-h-[calc(100vh-234px)] dark:text-light '>
        <Layout className='pt-0 md:pt-16 sm:pt-8 xl:pt-10'>
          <div className="flex items-center justify-between w-full lg:flex-col-reverse  sm:gap-4 md:gap-6 ">
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center md:gap-2 lg:gap-8'>
              <AnimatedText text={title} className="!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl" />
              <p className="my-4 text-base font-medium md:text-sm sm:text-sm">{description}</p>
              <div className='flex items-center mt-2 self-start lg:self-center'>
                <Link href="/amar_gupta_CV.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
                  download={true}
                >Resume<LinkArrow className={"w-6 ml-1"} />

                </Link>
                <Link href="mailto:amargupta272001@gmail.com"
                  className='ml-4 text-lg font-medium capitalize text-dark underline underline-offset-2 dark:text-light md:text-base'
                >Contact</Link>
              </div>
            </div>
            <div className='w-1/2 xs:w-full hidden md:inline-block'>
              <Image src={mobileProfilePic} alt="my-pic" className="rounded-full w-full h-auto lg:hidden md:inline-block md:w-full" priority sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 50vw" />
            </div>
            <div className='w-1/2 md:w-full md:hidden inline-block'>
              <Image src={profilePic} alt="my-pic" className="drop-shadow-profile w-full h-auto lg:hidden md:inline-block md:w-full" priority sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 50vw" />
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={programmingImg} alt="my-portfolio" className='w-full h-auto'></Image>
        </div>

      </main>
    </>
  )
}
